In [1]:
import os

os.chdir("..")

In [59]:
from problems import IntegerKnapsack

from fastqaoa.ctypes import qaoa
from fastqaoa.ctypes.optimize import optimize_qaoa_adam, optimize_qaoa_lbfgs
from fastqaoa.params import interpolate

from fastqaoa.ctypes.metrics import Metrics
import numpy as np

In [3]:
prb = IntegerKnapsack(weights=[36.0, 22.0, 41.0, 2.0, 18.0, 9.0], costs=[2.0, 20.0, 34.0, 18.0, 36.0, 40.0], max_capacity=60, id=-1, n_qubits=6)

In [4]:
mprb = IntegerKnapsack.get_instances()[6][0]

In [5]:
mprb

IntegerKnapsack(id=0, n_qubits=6, max_capacity=60, weights=array([56, 46, 44, 39,  7, 31]), costs=array([11,  0, 53, 30, 30, 55]))

In [6]:
prb

IntegerKnapsack(id=-1, n_qubits=6, max_capacity=60, weights=[36.0, 22.0, 41.0, 2.0, 18.0, 9.0], costs=[2.0, 20.0, 34.0, 18.0, 36.0, 40.0])

In [83]:
ks = IntegerKnapsack.get_instances()[6][0]

In [84]:
ks.costs

array([11,  0, 53, 30, 30, 55])

In [85]:
ks.weights

array([56, 46, 44, 39,  7, 31])

In [86]:
costs, weights = ks.diagonalized()
dg = costs.mask(weights, 0, weights.GTE)
dg = np.pi * dg / abs(dg.min_val)

In [87]:
def get_energy(betas, gammas):
    res = qaoa.qaoa(dg, betas, gammas).to_numpy()
    probs = np.abs(res) ** 2
    # print(probs)
    return probs.dot(dg.to_numpy())

In [88]:
get_energy([1], [1])

-0.43705215392279734

In [89]:
qaoa.grad_qaoa(dg, dg, [1., 2.], [4., 5.])

(-0.3034736982444905,
 array([0.75984601, 0.39969466]),
 array([0.1859147 , 0.07191195]))

In [90]:
# res = optimize_qaoa_adam(dg, dg, [1], [1], maxiter=100, tol=1e-5)

In [91]:
# print(res)

In [93]:
# params = interpolate(2, res.betas, res.gammas)

In [94]:
# qaoa.grad_qaoa(dg, dg, *params)

In [103]:
params = [1], [1]
for i in range(1, 16, 1):
    print(i)
    res = optimize_qaoa_lbfgs(dg, dg, *params)
    print(res.status, res.it)
    print(get_energy(res.betas, res.gammas))
    params = interpolate(i+1, res.betas, res.gammas)
    # print(params)
    # print(qaoa.grad_qaoa(dg, dg, *params)[0])
    # params = np.append(res.betas, 0.01), np.append(res.gammas, 0.01)

1
LBFGSStatus.Success 10
-0.4409824589870121
2
LBFGSStatus.Success 13
-1.2950019274149298
3
LBFGSStatus.Success 22
-1.9294464970409426
4
LBFGSStatus.Success 23
-2.448572914568092
5
LBFGSStatus.Success 29
-2.759112906210433
6
LBFGSStatus.Success 38
-2.946315133433959
7
LBFGSStatus.Success 47
-3.0289086549305595
8
LBFGSStatus.Success 91
-3.0505724003855765
9
LBFGSStatus.Success 129
-3.064899106479079
10
LBFGSStatus.Success 153
-3.078812333134928
11
LBFGSStatus.Success 184
-3.090152337654776
12
LBFGSStatus.Success 193
-3.1003006231016617
13
LBFGSStatus.Success 247
-3.1062743305949287
14
LBFGSStatus.Success 355
-3.1085715806494907
15
LBFGSStatus.Success 574
-3.109183344509973


In [96]:
params = np.append(res.betas, 0), np.append(res.gammas, 0)

In [97]:
print(get_energy(*params))

-3.1091833479462347


In [98]:
sv = qaoa.qaoa(dg, *params)

In [113]:
Metrics.compute(sv, dg, weights > 0).dump()

{'energy': -3.109183337946235,
 'approx_ratio': 0.9896837976093034,
 'feas_ratio': 0.9999999999999984,
 'feas_approx_ratio': 0.9896837976093049,
 'p_opt': 0.5643752246857106,
 'p_999': 0.5643752246857106,
 'p_99': 0.5643752246857106,
 'p_9': 0.9998824664299404,
 'min_val': -3.141592653589793,
 'rnd_val': -0.25236690985638593,
 'max_val': 0.0}

In [109]:
(weights > 0).to_numpy()

array([1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [112]:
co

In [ ]:
pri